### ISSUE TITLE
`cmake --build build` fails (error: 'atomic' file not found [clang-diagnostic-error]

### ISSUE THREAD

**Issue by th0mcat** [wazuh/wazuh-agent#482]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| latest? | Wazuh-Agent | Agent | Sources | Ubuntu 22.04.5 LTS |

I'm sure this is something I did to my OS, but when trying to build the agent I get the following error:

```c
[09:22:37] thomcat@server:~/wazuh-agent$ cmake --build build
[  1%] Building CXX object common/logger/CMakeFiles/Logger.dir/src/logger_unix.cpp.o
/home/thomcat/wazuh-agent/build/vcpkg_installed/x64-linux/include/spdlog/details/null_mutex.h:6:10: error: 'atomic' file not found [clang-diagnostic-error]
    6 | #include <atomic>
      |          ^~~~~~~~
2129 warnings and 1 error generated.
Error while processing /home/thomcat/wazuh-agent/src/common/logger/src/logger_unix.cpp.
Suppressed 2129 warnings (2129 in non-user code).
Use -header-filter=.* to display errors from all non-system headers. Use -system-headers to display errors from system headers as well.
Found compiler error(s).
gmake[2]: *** [common/logger/CMakeFiles/Logger.dir/build.make:76: common/logger/CMakeFiles/Logger.dir/src/logger_unix.cpp.o] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:1019: common/logger/CMakeFiles/Logger.dir/all] Error 2
gmake: *** [Makefile:136: all] Error 2
```

Confirmed I followed the build steps as presented, even `rm`'ed the folder and re-cloned the repo and tried again, same error.

**Comment by vikman90** [comment]
@th0mcat Per your log, I wonder if your C++ compiler if updated.

I can confirm that the agent build works with **g++ 11.4.0** (coming in Ubuntu 22.04):

```
g++ --version
```
```
g++ (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0
```

### Steps on Ubuntu 22.04

I've tested this script on `ubuntu:22.04` Docker image:

```shell
apt-get update
apt-get install -y cmake make gcc g++ git zip curl tar ninja-build pkg-config wget gnupg lsb-release software-properties-common libbz2-dev
wget https://apt.llvm.org/llvm.sh
chmod +x llvm.sh
./llvm.sh 18
apt-get update
apt-get install -y clang-tidy-18 autopoint libtool zlib1g-dev libgcrypt20-dev libmagic-dev libpopt-dev libmagic-dev libsqlite3-dev liblua5.4-dev gettext libarchive-dev

git clone --depth 1 https://github.com/wazuh/wazuh-agent.git
cd wazuh-agent
git submodule update --init --recursive
cmake src -B build
cmake --build build -j4
```

Please confirm your g++ version and let us know.
Best.

**Comment by th0mcat** [comment]
@vikman90 Thanks for the follow-up!  I can confirm my compiler is the same version.

```
[11:24:31] thomcat@server:~/wazuh-agent$ g++ --version
g++ (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0
```

I also updated `cmake` to 3.31.2 by [adding the kitware repository](https://askubuntu.com/questions/355565/how-do-i-install-the-latest-version-of-cmake-from-the-command-line) but that also didn't resolve the issue so I removed the repo and reinstalled cmake 3.22.1.

**Comment by th0mcat** [comment]
It appears I'm dumb, I was following the [BUILD.md build instructions](https://github.com/wazuh/wazuh-agent/blob/master/BUILD.md) without heading to the official documentation and seeing the other ways to install the agent.  My apologies, closing this out, thanks!

**Comment by vikman90** [comment]
No problem sir! We need to clarify and simplify the building process.

Best!
